server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: FifthPoint
          uri: https://github.com/yagolacoste/Tesis-Lacoste
          search-paths: config-data
  application:
    name: config-server
