server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: FifthPoint
          uri: https://github.com/yagolacoste/Tesis-Lacoste/tree
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  application:
    name: config-server
