server:
  port: 8082
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: FifthPoint
          uri: https://github.com/yagolacoste/Tesis-Lacoste
          searchPaths: config-data
