server:
  port: 9191
spring:
  application:
    name: api-gateway
  main:
    allow-circular-references: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/statistics/**
          filters:
            - AuthFilter
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/friendshiprequest/**
          filters:
            - AuthFilter
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/routes/**
          filters:
            - AuthFilter
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/battles/**
          filters:
            - AuthFilter
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/storeddocuments/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost


