-- MySQL Script generated by MySQL Workbench
-- Thu Jul 14 17:54:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bicycle
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bicycle` ;

-- -----------------------------------------------------
-- Schema bicycle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bicycle` DEFAULT CHARACTER SET latin1 ;
USE `bicycle` ;

-- -----------------------------------------------------
-- Table `bicycle`.`appuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`appuser` (
  `appuser` INT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_identity_type` VARCHAR(20) NOT NULL,
  `identity` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `age` INT(3) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`appuser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bicycle`.`coordinates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`coordinates` (
  `id_coordinates` INT(11) NOT NULL,
  `latitude` INT(11) NOT NULL,
  `length` INT(11) NOT NULL,
  PRIMARY KEY (`id_coordinates`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bicycle`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`route` (
  `id_route` INT(11) NOT NULL,
  `description` VARCHAR(255) NULL,
  `weather` JSON NOT NULL,
  PRIMARY KEY (`id_route`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bicycle`.`coordinates_has_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`coordinates_has_route` (
  `coordinates_id` INT(11) NOT NULL,
  `route_id` INT(11) NOT NULL,
  PRIMARY KEY (`coordinates_id`, `route_id`),
  CONSTRAINT `fk_coordenadas_has_recorrido_coordenadas1`
    FOREIGN KEY (`coordinates_id`)
    REFERENCES `bicycle`.`coordinates` (`id_coordinates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordenadas_has_recorrido_recorrido1`
    FOREIGN KEY (`route_id`)
    REFERENCES `bicycle`.`route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bicycle`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`statistics` (
  `id_statistics` INT(20) NOT NULL,
  `speed` INT(11) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `kilometros` INT(11) NOT NULL,
  PRIMARY KEY (`id_statistics`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bicycle`.`refresh_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`refresh_token` (
  `refresh_token` VARCHAR(150) NOT NULL,
  `token` VARCHAR(2048) NULL DEFAULT NULL,
  `appuser_id` INT(11) NOT NULL,
  `expired_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(4) NOT NULL,
  `active` TINYINT(4) NOT NULL,
  PRIMARY KEY (`refresh_token`),
  CONSTRAINT `fk_refresh_token_appuser1`
    FOREIGN KEY (`appuser_id`)
    REFERENCES `bicycle`.`appuser` (`appuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bicycle`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`friends` (
  `appuser_id` INT(20) NOT NULL,
  `appuser_id_friends` INT(20) NOT NULL,
  PRIMARY KEY (`appuser_id`, `appuser_id_friends`),
  CONSTRAINT `fk_appuser_has_appuser_appuser1`
    FOREIGN KEY (`appuser_id`)
    REFERENCES `bicycle`.`appuser` (`appuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appuser_has_appuser_appuser2`
    FOREIGN KEY (`appuser_id_friends`)
    REFERENCES `bicycle`.`appuser` (`appuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bicycle`.`appuser_has_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle`.`appuser_has_route` (
  `appuser_appuser` INT(20) NOT NULL,
  `route_id_route` INT(11) NOT NULL,
  `statistics_id` INT(20) NOT NULL,
  PRIMARY KEY (`appuser_appuser`, `route_id_route`, `statistics_id`),
  CONSTRAINT `fk_appuser_has_recorrido_appuser1`
    FOREIGN KEY (`appuser_appuser`)
    REFERENCES `bicycle`.`appuser` (`appuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appuser_has_recorrido_recorrido1`
    FOREIGN KEY (`route_id_route`)
    REFERENCES `bicycle`.`route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appuser_has_route_statistics1`
    FOREIGN KEY (`statistics_id`)
    REFERENCES `bicycle`.`statistics` (`id_statistics`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
